/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects/{id}/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 프로젝트 Webhook URL 조회 */
        get: operations["getWebhook"];
        /** 프로젝트 Webhook URL 설정 */
        put: operations["updateWebhook"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/type-assignees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 타입별 담당자 기본값 조회 */
        get: operations["getTypeAssignees"];
        /**
         * 타입별 담당자 기본값 수정
         * @description 문서 타입별 기본 담당자를 전체 replace 의미로 설정한다. assigneeMemberId는 워크스페이스 멤버 ID이며, null이면 담당자 없음을 의미한다. 빈 list는 전체 row 삭제.
         */
        put: operations["updateTypeAssignees"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 프로젝트 목록
         * @description 본인이 ProjectMember로 배정된 프로젝트만 반환. 비멤버는 빈 list.
         */
        get: operations["list"];
        put?: never;
        /**
         * 프로젝트 생성
         * @description Notion 루트 페이지를 기준으로 프로젝트를 생성한다. 생성 직후 동기화는 실행되지 않는다. 카테고리 등록·담당자 기본값·멤버 배정을 완료한 후 POST /projects/{id}/sync로 초기 동기화를 수동 트리거해야 한다.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 멤버 초대
         * @description 워크스페이스 멤버로 초대한다. 가입 사용자만 이메일로 검색해 추가. 초대된 멤버는 프로젝트 배정 후보군이 되며, 개별 프로젝트에 배정되기 전까지는 어떤 프로젝트에도 접근할 수 없다.
         */
        post: operations["inviteMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/notion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Notion Webhook 수신 (page.content_updated / page.moved) */
        post: operations["receiveWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 수동 동기화 트리거
         * @description Notion 루트 페이지 하위 트리를 전체 조회해 문서 스냅샷을 갱신하고, 엣지·연결 제안 생성을 시작한다. 프로젝트 생성 후 카테고리·담당자 기본값·멤버 배정이 끝난 뒤 호출한다. ProjectSyncTriggeredEvent 발행만 — document worker가 listen.
         */
        post: operations["sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 룰 목록
         * @description 프로젝트에 적용 가능한 룰(기본 제공 + 커스텀)을 반환한다.
         */
        get: operations["listRules"];
        put?: never;
        /** 커스텀 룰 추가 */
        post: operations["createRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/proposals/{proposalId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 연결 제안 수락
         * @description EdgeProposal을 DependencyEdge로 전환하고 정합성 검증을 즉시 트리거한다. 수락 후 해당 proposal은 삭제된다.
         */
        post: operations["acceptProposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 프로젝트 멤버 배정 */
        post: operations["assignMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/edges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 엣지 목록 (관리 패널용) */
        get: operations["listEdges"];
        put?: never;
        /** 커스텀 엣지 추가 */
        post: operations["createEdge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 카테고리 목록 */
        get: operations["getCategories"];
        put?: never;
        /**
         * 카테고리 등록
         * @description 프로젝트 루트 페이지의 직계 자식 페이지를 카테고리로 등록하고 문서 타입을 매핑한다. 문서는 자기 조상 라인의 카테고리 매핑을 조회해 타입을 결정한다.
         */
        post: operations["registerCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conflicts/{id}/ignore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 충돌 수동 무시
         * @description 충돌을 무시 상태로 마킹한다. 무시된 충돌은 해당 문서 쌍 중 하나가 외부에서 변경되어 재검증이 실행되면 자동으로 해제된다.
         */
        post: operations["ignore"];
        /** 충돌 무시 해제 */
        delete: operations["unignore"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conflicts/{conflictId}/findings/{findingId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 충돌 finding 수정 제안 승인
         * @description AI가 생성한 수정 제안을 사용자가 승인한다. target 문서가 조회 시점 이후 변경되었으면 stale 409. 승인 시 ProposalApprovedEvent를 발행하여 document 도메인이 Notion 쓰기를 처리한다.
         */
        post: operations["approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 프로젝트 멤버 제거 */
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        /** 프로젝트 멤버 역할 변경 */
        patch: operations["updateMemberRole"];
        trace?: never;
    };
    "/projects/{id}/categories/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 카테고리 제거 */
        delete: operations["removeCategory"];
        options?: never;
        head?: never;
        /** 카테고리 타입 변경 */
        patch: operations["changeCategoryType"];
        trace?: never;
    };
    "/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 워크스페이스 목록 — 소유 + 멤버 참여 모두 */
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/notion-pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Notion 최상위 페이지 목록
         * @description 프로젝트 생성 위저드 루트 페이지 후보. 워크스페이스 최상위 Notion 페이지를 라이브 조회한다. 워크스페이스 생성자 전용.
         */
        get: operations["listRootPages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/notion-pages/{pageId}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Notion 페이지 직계 자식 목록
         * @description 프로젝트 생성 위저드 카테고리 매핑 대상. 페이지의 직계 자식 Notion 페이지를 라이브 조회한다. 워크스페이스 생성자 전용.
         */
        get: operations["listChildPages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 워크스페이스 상세 */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 프로젝트 상세 */
        get: operations["get_1"];
        put?: never;
        post?: never;
        /** 프로젝트 삭제 */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/validation-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 검증 작업 이력 */
        get: operations["listValidationTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 연결 제안 목록 (관리 패널용) */
        get: operations["listProposals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 그래프 전체 데이터 (캔버스 초기 렌더링용)
         * @description 캔버스 초기 렌더링에 필요한 nodes·edges·proposals를 한 번에 반환한다. edges는 실선 의존 관계, proposals는 점선 연결 후보다. 패널·관리 목록이 필요할 때는 개별 list API를 사용한다.
         */
        get: operations["getGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 문서 목록 */
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 프로젝트 충돌 목록 */
        get: operations["listByProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth2/authorization/notion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notion OAuth2 인증 시작 */
        get: operations["oauthStart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 인박스
         * @description 내가 담당자인 문서가 target인 충돌 목록을 배정된 모든 프로젝트에 걸쳐 반환한다. 라우팅: (1) 직접 담당 (Document.assigneeMemberId), (2) type 매핑 (TypeAssigneeDefault), (3) Admin 프로젝트의 미할당 문서. status=ACTIVE(default)|IGNORED|ALL.
         */
        get: operations["myInbox"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login/oauth2/code/notion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notion OAuth2 콜백 */
        get: operations["oauthCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 문서 상세 */
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 현재 로그인 사용자 정보 */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{id}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 멤버 제거 */
        delete: operations["removeMember_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/rules/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 룰 삭제 */
        delete: operations["deleteRule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/proposals/{proposalId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 연결 제안 거절 */
        delete: operations["rejectProposal"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/edges/{edgeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 엣지 삭제 */
        delete: operations["deleteEdge"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 로그아웃 */
        delete: operations["logout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateWebhookRequest: {
            /**
             * @description Slack 또는 Discord Incoming Webhook URL
             * @example https://hooks.slack.com/services/xxx/yyy/zzz
             */
            url?: string;
        };
        TypeAssigneeItem: {
            /**
             * @description 문서 타입
             * @enum {string}
             */
            documentType?: "meeting_notes" | "planning" | "requirements" | "design" | "research";
            /**
             * Format: int64
             * @description 담당자 워크스페이스 멤버 ID (null이면 담당자 없음)
             * @example 1
             */
            assigneeMemberId?: number | null;
        };
        UpdateTypeAssigneesRequest: {
            /** @description 타입별 담당자 기본값 목록 */
            assignees?: components["schemas"]["TypeAssigneeItem"][];
        };
        CreateProjectRequest: {
            /**
             * @description 프로젝트 이름
             * @example Q2 Planning
             */
            name?: string;
            /**
             * @description Notion 루트 페이지 ID
             * @example abc1234567890def
             */
            notionRootPageId?: string;
        };
        IdResponse: {
            /**
             * Format: int64
             * @description 생성된 리소스 ID
             * @example 1
             */
            id?: number;
        };
        InviteMemberRequest: {
            /**
             * @description 초대할 가입 사용자 이메일
             * @example user@example.com
             */
            email?: string;
        };
        NotionActor: {
            /**
             * @description actor ID
             * @example c7c11cca-1d73-471d-9b6e-bdef51470190
             */
            id?: string;
            /**
             * @description actor 타입 (person / bot)
             * @example person
             */
            type?: string;
        };
        NotionEntity: {
            /**
             * @description 엔티티 ID (페이지 ID)
             * @example abc1234567890def
             */
            id?: string;
            /**
             * @description 엔티티 타입
             * @example page
             */
            type?: string;
        };
        NotionWebhookPayload: {
            /** @description 웹훅 이벤트 고유 ID */
            id?: string;
            /**
             * @description 이벤트 발생 시각 (ISO 8601)
             * @example 2024-12-05T19:49:36.997Z
             */
            timestamp?: string;
            /**
             * @description 이벤트 타입 (page.content_updated / page.moved)
             * @example page.content_updated
             */
            type?: string;
            /** @description 워크스페이스 ID */
            workspaceId?: string;
            /** @description 웹훅 구독 ID */
            subscriptionId?: string;
            /** @description 이벤트를 트리거한 엔티티 */
            entity?: components["schemas"]["NotionEntity"];
            /** @description 이벤트 작성자 목록 */
            authors?: components["schemas"]["NotionActor"][];
            /**
             * Format: int32
             * @description 전달 시도 횟수 (최대 8회)
             * @example 1
             */
            attemptNumber?: number;
        };
        CreateRuleRequest: {
            /**
             * @description 출발 문서 타입
             * @enum {string}
             */
            sourceType?: "meeting_notes" | "planning" | "requirements" | "design" | "research";
            /**
             * @description 도착 문서 타입
             * @enum {string}
             */
            targetType?: "meeting_notes" | "planning" | "requirements" | "design" | "research";
            /**
             * @description 검증 기준
             * @example 범위 일치 여부
             */
            validationCriterion?: string;
        };
        AssignMemberRequest: {
            /**
             * Format: int64
             * @description 배정할 워크스페이스 멤버 ID
             * @example 1
             */
            workspaceMemberId?: number;
            /**
             * @description 역할
             * @enum {string}
             */
            role?: "ADMIN" | "MEMBER";
        };
        CreateEdgeRequest: {
            /**
             * Format: int64
             * @description 출발 문서 ID (source 내용이 target에 반영되어야 함)
             * @example 1
             */
            sourceDocumentId?: number;
            /**
             * Format: int64
             * @description 도착 문서 ID
             * @example 2
             */
            targetDocumentId?: number;
            /**
             * @description 검증 기준
             * @example 범위 일치 여부
             */
            validationCriterion?: string;
        };
        RegisterCategoryRequest: {
            /**
             * @description Notion 페이지 ID
             * @example abc1234567890def
             */
            notionPageId?: string;
            /**
             * @description 문서 타입
             * @enum {string}
             */
            documentType?: "meeting_notes" | "planning" | "requirements" | "design" | "research";
        };
        IgnoreConflictRequest: {
            /**
             * @description 무시 사유 (선택)
             * @example 의도된 차이로 확인됨
             */
            reason?: string | null;
        };
        ApproveProposalRequest: {
            /**
             * Format: date-time
             * @description 조회 시점에 본 target 문서의 notionLastEditedAt — server-side stale 비교에 사용 (target 측이 한 번도 동기화되지 않았다면 null)
             */
            expectedTargetNotionLastEditedAt?: string | null;
        };
        UpdateProjectMemberRoleRequest: {
            /**
             * @description 변경할 역할
             * @enum {string}
             */
            role?: "ADMIN" | "MEMBER";
        };
        ChangeCategoryTypeRequest: {
            /**
             * @description 변경할 문서 타입
             * @enum {string}
             */
            documentType?: "meeting_notes" | "planning" | "requirements" | "design" | "research";
        };
        WorkspaceSummary: {
            /**
             * Format: int64
             * @description 워크스페이스 ID
             * @example 1
             */
            id?: number;
            /**
             * @description 워크스페이스 이름
             * @example My Team
             */
            name?: string;
            /**
             * Format: int32
             * @description 워크스페이스에 직접 초대된 멤버 수
             * @example 7
             */
            memberCount?: number;
            /**
             * Format: int32
             * @description 워크스페이스 내 프로젝트 수
             * @example 3
             */
            projectCount?: number;
            /**
             * Format: int64
             * @description 워크스페이스 내 모든 프로젝트의 동기화된 문서 합산
             * @example 120
             */
            documentCount?: number;
            /**
             * Format: int64
             * @description 워크스페이스 내 모든 프로젝트의 미해소(active 미무시) 충돌 합산
             * @example 5
             */
            unresolvedConflictCount?: number;
            /**
             * Format: date-time
             * @description 워크스페이스 내 모든 프로젝트 중 Notion 측 최근 변경 시각 max
             */
            lastNotionChangedAt?: string | null;
        };
        ProjectSummary: {
            /**
             * Format: int64
             * @description 프로젝트 ID
             * @example 1
             */
            id?: number;
            /**
             * @description 프로젝트 이름
             * @example Q2 Planning
             */
            name?: string;
            /**
             * Format: int32
             * @description 프로젝트에 배정된 멤버 수
             * @example 5
             */
            memberCount?: number;
            /**
             * Format: int64
             * @description 동기화된 문서 수
             * @example 42
             */
            documentCount?: number;
            /**
             * Format: int64
             * @description 미해소(active 미무시) 충돌 수
             * @example 3
             */
            unresolvedConflictCount?: number;
            /**
             * Format: date-time
             * @description 프로젝트 내 문서의 Notion 측 최근 변경 시각
             */
            lastNotionChangedAt?: string | null;
        };
        IconResponse: {
            /**
             * @description 아이콘 타입 — EMOJI는 이모지 문자, EXTERNAL은 외부 URL, FILE은 Notion signed URL(만료 가능)
             * @enum {string}
             */
            type?: "EMOJI" | "EXTERNAL" | "FILE";
            /**
             * @description 타입에 따른 값 — emoji면 이모지 문자, external/file이면 URL
             * @example 📄
             */
            value?: string;
        };
        NotionPageRef: {
            /**
             * @description Notion 페이지 ID — 프로젝트 생성·카테고리 등록 API 입력에 사용
             * @example abc1234567890def
             */
            notionPageId?: string;
            /**
             * @description 페이지 제목 (드롭다운·카테고리 화면 표시용)
             * @example Q2 Planning
             */
            title?: string;
            icon?: components["schemas"]["IconResponse"] | null;
        };
        WorkspaceDetail: {
            /**
             * Format: int64
             * @description 워크스페이스 ID
             * @example 1
             */
            id?: number;
            /**
             * @description 워크스페이스 이름
             * @example My Team
             */
            name?: string;
            members?: components["schemas"]["WorkspaceMemberSummary"][];
            /**
             * Format: int32
             * @description 워크스페이스에 직접 초대된 멤버 수
             * @example 7
             */
            memberCount?: number;
            /**
             * Format: int32
             * @description 워크스페이스 내 프로젝트 수
             * @example 3
             */
            projectCount?: number;
            /**
             * Format: int64
             * @description 워크스페이스 내 모든 프로젝트의 동기화된 문서 합산
             * @example 120
             */
            documentCount?: number;
            /**
             * Format: int64
             * @description 워크스페이스 내 모든 프로젝트의 미해소(active 미무시) 충돌 합산
             * @example 5
             */
            unresolvedConflictCount?: number;
            /**
             * Format: date-time
             * @description 워크스페이스 내 모든 프로젝트 중 Notion 측 최근 변경 시각 max
             */
            lastNotionChangedAt?: string | null;
        };
        WorkspaceMemberSummary: {
            /**
             * Format: int64
             * @description 사용자 ID
             * @example 1
             */
            userId?: number;
            /**
             * @description 이름
             * @example 홍길동
             */
            name?: string;
            /**
             * @description 이메일
             * @example user@example.com
             */
            email?: string;
            /**
             * Format: date-time
             * @description 워크스페이스 가입 시점
             */
            joinedAt?: string;
        };
        ProjectDetail: {
            /**
             * Format: int64
             * @description 프로젝트 ID
             * @example 1
             */
            id?: number;
            /**
             * @description 프로젝트 이름
             * @example Q2 Planning
             */
            name?: string;
            /**
             * @description Notion 루트 페이지 ID
             * @example abc1234567890def
             */
            notionRootPageId?: string;
            members?: components["schemas"]["ProjectMemberSummary"][];
            /**
             * Format: int32
             * @description 프로젝트에 배정된 멤버 수
             * @example 5
             */
            memberCount?: number;
            /**
             * Format: int64
             * @description 동기화된 문서 수
             * @example 42
             */
            documentCount?: number;
            /**
             * Format: int64
             * @description 미해소(active 미무시) 충돌 수
             * @example 3
             */
            unresolvedConflictCount?: number;
            /**
             * Format: date-time
             * @description 프로젝트 내 문서의 Notion 측 최근 변경 시각
             */
            lastNotionChangedAt?: string | null;
        };
        ProjectMemberSummary: {
            /**
             * Format: int64
             * @description 멤버 ID
             * @example 1
             */
            id?: number;
            /**
             * @description 이름
             * @example 홍길동
             */
            name?: string;
            /**
             * @description 역할
             * @enum {string}
             */
            role?: "ADMIN" | "MEMBER";
        };
        WebhookResponse: {
            /**
             * @description 설정된 Webhook URL (미설정 시 null)
             * @example https://hooks.slack.com/services/xxx/yyy/zzz
             */
            url?: string | null;
        };
        PageResponseValidationTaskResponse: {
            content?: components["schemas"]["ValidationTaskResponse"][];
            /**
             * Format: int64
             * @description 전체 항목 수
             * @example 100
             */
            totalElements?: number;
            /**
             * Format: int32
             * @description 전체 페이지 수
             * @example 5
             */
            totalPages?: number;
            /**
             * Format: int32
             * @description 현재 페이지 (0-based)
             * @example 0
             */
            page?: number;
            /**
             * Format: int32
             * @description 페이지 크기
             * @example 20
             */
            size?: number;
        };
        ValidationTaskResponse: {
            /**
             * Format: int64
             * @description 검증 작업 ID
             * @example 1
             */
            id?: number;
            /**
             * Format: int64
             * @description 검증 대상 엣지 ID
             * @example 1
             */
            edgeId?: number;
            /**
             * @description 검증 상태
             * @enum {string}
             */
            status?: "PENDING" | "SUCCESS" | "FAILED";
            /**
             * Format: date-time
             * @description 생성 시각
             */
            createdAt?: string;
        };
        TypeAssigneeResponse: {
            /**
             * @description 문서 타입
             * @enum {string}
             */
            documentType?: "meeting_notes" | "planning" | "requirements" | "design" | "research";
            /**
             * Format: int64
             * @description 담당자 워크스페이스 멤버 ID (null이면 담당자 없음)
             * @example 1
             */
            assigneeMemberId?: number | null;
        };
        RuleResponse: {
            /**
             * Format: int64
             * @description 룰 ID
             * @example 1
             */
            id?: number;
            /**
             * Format: int64
             * @description 소속 프로젝트 ID (기본 제공 룰은 null)
             * @example 1
             */
            projectId?: number | null;
            /**
             * @description 출발 문서 타입
             * @enum {string}
             */
            sourceType?: "meeting_notes" | "planning" | "requirements" | "design" | "research";
            /**
             * @description 도착 문서 타입
             * @enum {string}
             */
            targetType?: "meeting_notes" | "planning" | "requirements" | "design" | "research";
            /**
             * @description 검증 기준
             * @example 범위 일치 여부
             */
            validationCriterion?: string;
            default?: boolean;
        };
        EdgeProposalResponse: {
            /**
             * Format: int64
             * @description 연결 제안 ID
             * @example 1
             */
            id?: number;
            /**
             * Format: int64
             * @description 출발 문서 ID
             * @example 1
             */
            sourceDocumentId?: number;
            /**
             * Format: int64
             * @description 도착 문서 ID
             * @example 2
             */
            targetDocumentId?: number;
            /**
             * Format: double
             * @description 유사도 점수 (0.0 ~ 1.0)
             * @example 0.87
             */
            similarityScore?: number;
            /**
             * @description 수락 시 적용될 검증 기준 (룰 기반 자동 매칭)
             * @example 범위 일치 여부
             */
            validationCriterion?: string;
        };
        EdgeResponse: {
            /**
             * Format: int64
             * @description 엣지 ID
             * @example 1
             */
            id?: number;
            /**
             * Format: int64
             * @description 출발 문서 ID
             * @example 1
             */
            sourceDocumentId?: number;
            /**
             * Format: int64
             * @description 도착 문서 ID
             * @example 2
             */
            targetDocumentId?: number;
            /**
             * @description 검증 기준
             * @example 범위 일치 여부
             */
            validationCriterion?: string;
            /**
             * @description 충돌 상태
             * @enum {string}
             */
            conflictStatus?: "NONE" | "CONFLICT";
            /**
             * @description 엣지 생성 출처 (Notion 링크/멘션 기반, 제안 수락, 수동 추가)
             * @enum {string}
             */
            source?: "NOTION_REFERENCE" | "PROPOSAL_ACCEPTED" | "CUSTOM";
            /**
             * Format: int64
             * @description 엣지 생성에 사용된 룰 ID (수동 추가 엣지는 null)
             * @example 1
             */
            ruleId?: number | null;
        };
        GraphNodeResponse: {
            /**
             * Format: int64
             * @description 문서 ID
             * @example 1
             */
            id?: number;
            /**
             * @description 문서 제목
             * @example 2024-01 스프린트 회의록
             */
            title?: string;
            /**
             * @description 문서 타입 (project type-mapping 미분류 시 null)
             * @enum {string|null}
             */
            type?: "meeting_notes" | "planning" | "requirements" | "design" | "research" | null;
            /**
             * Format: int64
             * @description 담당자 워크스페이스 멤버 ID (없으면 null)
             * @example 1
             */
            assigneeMemberId?: number | null;
        };
        ProjectGraphResponse: {
            nodes?: components["schemas"]["GraphNodeResponse"][];
            edges?: components["schemas"]["EdgeResponse"][];
            proposals?: components["schemas"]["EdgeProposalResponse"][];
        };
        DocumentSummary: {
            /**
             * Format: int64
             * @description 문서 ID
             * @example 1
             */
            id?: number;
            /**
             * @description Notion 페이지 ID
             * @example abc1234567890def
             */
            notionPageId?: string;
            /**
             * @description 문서 제목
             * @example 2024-01 스프린트 회의록
             */
            title?: string;
            /**
             * @description 문서 타입 (project type-mapping 미분류 시 null)
             * @enum {string|null}
             */
            type?: "meeting_notes" | "planning" | "requirements" | "design" | "research" | null;
            /**
             * Format: int64
             * @description 부모 Document ID (루트 또는 프로젝트 경계 밖이면 null)
             * @example 1
             */
            parentDocumentId?: number | null;
            icon?: components["schemas"]["IconResponse"] | null;
        };
        PageResponseDocumentSummary: {
            content?: components["schemas"]["DocumentSummary"][];
            /**
             * Format: int64
             * @description 전체 항목 수
             * @example 100
             */
            totalElements?: number;
            /**
             * Format: int32
             * @description 전체 페이지 수
             * @example 5
             */
            totalPages?: number;
            /**
             * Format: int32
             * @description 현재 페이지 (0-based)
             * @example 0
             */
            page?: number;
            /**
             * Format: int32
             * @description 페이지 크기
             * @example 20
             */
            size?: number;
        };
        ConflictFindingResponse: {
            /**
             * Format: int64
             * @description 충돌 finding ID
             * @example 1
             */
            id?: number;
            /** @description source 측 충돌 블록 ID 목록 (Notion block id) */
            sourceBlockIds?: string[];
            /** @description target 측 충돌 블록 ID (Notion block id) */
            targetBlockId?: string;
            /**
             * @description 충돌 근거 (AI 판정)
             * @example planning 3.2절 결정사항이 requirements에 반영되지 않음
             */
            rationale?: string;
            /**
             * @description target 블록을 교체할 새 텍스트 (replace patch)
             * @example requirements 3.2절을 'A 옵션 선택'으로 변경
             */
            newText?: string;
            /**
             * @description 충돌 사안 한 줄 요약 제목
             * @example 결정사항 미반영
             */
            title?: string;
            /**
             * Format: date-time
             * @description 감지 시각
             */
            detectedAt?: string;
        };
        ConflictResponse: {
            /**
             * Format: int64
             * @description 충돌 ID
             * @example 1
             */
            id?: number;
            /**
             * Format: int64
             * @description 연결된 엣지 ID
             * @example 1
             */
            edgeId?: number;
            /**
             * Format: int64
             * @description 출발 문서 ID
             * @example 1
             */
            sourceDocumentId?: number;
            /**
             * Format: int64
             * @description 도착 문서 ID
             * @example 2
             */
            targetDocumentId?: number;
            /** @description 충돌 finding 목록 */
            findings?: components["schemas"]["ConflictFindingResponse"][];
            /**
             * Format: date-time
             * @description 무시 처리 시각 (미무시 시 null)
             */
            ignoredAt?: string | null;
            /**
             * @description 무시 사유 (선택)
             * @example 의도된 차이로 확인됨
             */
            ignoreReason?: string | null;
        };
        PageResponseConflictResponse: {
            content?: components["schemas"]["ConflictResponse"][];
            /**
             * Format: int64
             * @description 전체 항목 수
             * @example 100
             */
            totalElements?: number;
            /**
             * Format: int32
             * @description 전체 페이지 수
             * @example 5
             */
            totalPages?: number;
            /**
             * Format: int32
             * @description 현재 페이지 (0-based)
             * @example 0
             */
            page?: number;
            /**
             * Format: int32
             * @description 페이지 크기
             * @example 20
             */
            size?: number;
        };
        CategoryResponse: {
            /**
             * Format: int64
             * @description 카테고리 ID
             * @example 1
             */
            id?: number;
            /**
             * @description Notion 페이지 ID
             * @example abc1234567890def
             */
            notionPageId?: string;
            /**
             * @description 문서 타입
             * @enum {string}
             */
            documentType?: "meeting_notes" | "planning" | "requirements" | "design" | "research";
        };
        InboxDocumentRef: {
            /** Format: int64 */
            id?: number;
            title?: string;
            /** @enum {string|null} */
            type?: "meeting_notes" | "planning" | "requirements" | "design" | "research" | null;
        };
        MyConflictRow: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            edgeId?: number;
            /** Format: int64 */
            projectId?: number;
            projectName?: string;
            sourceDocument?: components["schemas"]["InboxDocumentRef"];
            targetDocument?: components["schemas"]["InboxDocumentRef"];
            title?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "IGNORED";
            /** Format: date-time */
            firstDetectedAt?: string;
            /** Format: date-time */
            ignoredAt?: string | null;
        };
        PageResponseMyConflictRow: {
            content?: components["schemas"]["MyConflictRow"][];
            /**
             * Format: int64
             * @description 전체 항목 수
             * @example 100
             */
            totalElements?: number;
            /**
             * Format: int32
             * @description 전체 페이지 수
             * @example 5
             */
            totalPages?: number;
            /**
             * Format: int32
             * @description 현재 페이지 (0-based)
             * @example 0
             */
            page?: number;
            /**
             * Format: int32
             * @description 페이지 크기
             * @example 20
             */
            size?: number;
        };
        Block: {
            blockId?: string;
            parentBlockId?: string | null;
            type?: string;
            text?: string | null;
            /** Format: int32 */
            order?: number;
        };
        DocumentDetail: {
            /**
             * Format: int64
             * @description 문서 ID
             * @example 1
             */
            id?: number;
            /**
             * @description Notion 페이지 ID
             * @example abc1234567890def
             */
            notionPageId?: string;
            /**
             * @description 문서 제목
             * @example 2024-01 스프린트 회의록
             */
            title?: string;
            /**
             * @description 문서 타입 (project type-mapping 미분류 시 null)
             * @enum {string|null}
             */
            type?: "meeting_notes" | "planning" | "requirements" | "design" | "research" | null;
            /**
             * Format: int64
             * @description 부모 Document ID (루트 또는 프로젝트 경계 밖이면 null)
             * @example 1
             */
            parentDocumentId?: number | null;
            icon?: components["schemas"]["IconResponse"] | null;
            /**
             * Format: int64
             * @description 담당자 워크스페이스 멤버 ID (없으면 null)
             * @example 1
             */
            assigneeMemberId?: number | null;
            /**
             * Format: date-time
             * @description Notion 원본의 마지막 수정 시각 (미동기화 시 null)
             */
            notionLastEditedAt?: string | null;
            /** @description 블록 row 목록 */
            blocks?: components["schemas"]["Block"][];
        };
        UserResponse: {
            /**
             * Format: int64
             * @description 사용자 ID
             * @example 1
             */
            id?: number;
            /**
             * @description 이메일
             * @example user@example.com
             */
            email?: string;
            /**
             * @description 이름
             * @example 홍길동
             */
            name?: string;
            /**
             * @description 아바타 이미지 URL (Notion 프로필 사진, 없으면 null)
             * @example https://example.com/avatar.png
             */
            avatarUrl?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 완료 — 미설정 시 url null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WebhookResponse"];
                };
            };
            /** @description 프로젝트 없음 또는 호출자가 Project Admin 아님 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWebhookRequest"];
            };
        };
        responses: {
            /** @description 설정 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 호출자가 Project Admin 아님 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTypeAssignees: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TypeAssigneeResponse"][];
                };
            };
            /** @description 프로젝트 없음 또는 본인 비멤버 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateTypeAssignees: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTypeAssigneesRequest"];
            };
        };
        responses: {
            /** @description 설정 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 호출자가 Project Admin 아님 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 프로젝트 없음 또는 assignee가 프로젝트의 워크스페이스에 속하지 않음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectSummary"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description 생성 완료 — project row id 반환 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IdResponse"];
                };
            };
            /** @description 호출자가 워크스페이스 생성자 아님 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 워크스페이스 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    inviteMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteMemberRequest"];
            };
        };
        responses: {
            /** @description 초대 완료 — workspace_member row id 반환 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IdResponse"];
                };
            };
            /** @description 호출자가 워크스페이스 생성자 아님 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 워크스페이스 없음 또는 invitee 이메일이 가입 사용자에 매칭 안 됨 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 자기 자신 초대 또는 이미 멤버 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    receiveWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotionWebhookPayload"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sync: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 트리거 완료 (이벤트 발행) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 호출자가 Project Admin 아님 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 프로젝트 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 룰 목록 (기본 + 커스텀) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RuleResponse"][];
                };
            };
            /** @description 프로젝트 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RuleResponse"][];
                };
            };
        };
    };
    createRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRuleRequest"];
            };
        };
        responses: {
            /** @description 룰 생성 완료 — graph_rule row id 반환 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IdResponse"];
                };
            };
            /** @description source/target 타입 동일 등 요청 유효성 위반 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 프로젝트 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 동일 (source_type, target_type) 룰이 프로젝트에 이미 존재 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    acceptProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                proposalId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 수락 완료 — 생성된 dependency_edge row id 반환 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IdResponse"];
                };
            };
            /** @description 제안 없음 또는 다른 프로젝트 소속 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    assignMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignMemberRequest"];
            };
        };
        responses: {
            /** @description 배정 완료 — project_member row id 반환 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IdResponse"];
                };
            };
            /** @description 호출자가 Project Admin 아님 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 프로젝트 없음 또는 workspace_member가 프로젝트의 워크스페이스에 속하지 않음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 이미 프로젝트 멤버 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listEdges: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 엣지 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EdgeResponse"][];
                };
            };
            /** @description 프로젝트 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EdgeResponse"][];
                };
            };
        };
    };
    createEdge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEdgeRequest"];
            };
        };
        responses: {
            /** @description 엣지 생성 완료 — dependency_edge row id 반환 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IdResponse"];
                };
            };
            /** @description source/target 문서 동일 등 요청 유효성 위반 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 프로젝트 또는 문서 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 동일 방향 엣지가 이미 존재 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCategories: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryResponse"][];
                };
            };
            /** @description 프로젝트 없음 또는 본인 비멤버 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    registerCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterCategoryRequest"];
            };
        };
        responses: {
            /** @description 등록 완료 — category row id 반환 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IdResponse"];
                };
            };
            /** @description 호출자가 Project Admin 아님 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 프로젝트 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 같은 notion_page_id 카테고리 이미 존재 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ignore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IgnoreConflictRequest"];
            };
        };
        responses: {
            /** @description 무시 마킹 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 충돌 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 이미 무시 상태 또는 이미 해소된 충돌 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unignore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 무시 해제 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 충돌 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 무시 상태가 아닌 충돌 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conflictId: number;
                findingId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveProposalRequest"];
            };
        };
        responses: {
            /** @description 승인 완료 + ProposalApprovedEvent 발행 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 충돌 또는 finding 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 이미 승인된 finding 또는 target 문서가 조회 시점 이후 변경 (stale) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                memberId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 제거 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 자기 자신 제거 시도 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 호출자가 Project Admin 아님 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 프로젝트 없음 또는 project_member 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                memberId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectMemberRoleRequest"];
            };
        };
        responses: {
            /** @description 변경 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 자기 자신 역할 변경 시도 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 호출자가 Project Admin 아님 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 프로젝트 없음 또는 project_member 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                categoryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 제거 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 호출자가 Project Admin 아님 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 프로젝트 또는 카테고리 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    changeCategoryType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                categoryId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeCategoryTypeRequest"];
            };
        };
        responses: {
            /** @description 변경 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 호출자가 Project Admin 아님 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 프로젝트 또는 카테고리 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 워크스페이스 목록 (접근 가능한 것 없으면 빈 배열) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceSummary"][];
                };
            };
        };
    };
    listRootPages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotionPageRef"][];
                };
            };
            /** @description 호출자가 워크스페이스 생성자 아님 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 워크스페이스 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listChildPages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
                pageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotionPageRef"][];
                };
            };
            /** @description 호출자가 워크스페이스 생성자 아님 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 워크스페이스 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 워크스페이스 상세 (멤버 목록 포함) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceDetail"];
                };
            };
            /** @description 워크스페이스 없음 또는 접근 권한 없음 (구분 X — security 측면에서 동일 응답) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceDetail"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description 프로젝트 없음 또는 본인 비멤버 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 호출자가 Project Admin 아님 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 프로젝트 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listValidationTasks: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 검증 작업 이력 page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseValidationTaskResponse"];
                };
            };
        };
    };
    listProposals: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 연결 제안 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EdgeProposalResponse"][];
                };
            };
            /** @description 프로젝트 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EdgeProposalResponse"][];
                };
            };
        };
    };
    getGraph: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 그래프 데이터 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectGraphResponse"];
                };
            };
            /** @description 프로젝트 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectGraphResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 프로젝트 문서 목록 page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseDocumentSummary"];
                };
            };
        };
    };
    listByProject: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 충돌 목록 (없으면 빈 page) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseConflictResponse"];
                };
            };
        };
    };
    oauthStart: {
        parameters: {
            query?: {
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notion authorization URL로 redirect */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    myInbox: {
        parameters: {
            query?: {
                status?: "ACTIVE" | "IGNORED" | "ALL";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 인박스 목록 (없으면 빈 page) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseMyConflictRow"];
                };
            };
        };
    };
    oauthCallback: {
        parameters: {
            query?: {
                code?: string;
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 시 success redirect URI로, 실패 시 동 URI에 `?oauth=error` 부착 */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 문서 상세 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description 문서 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentDetail"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 사용자 정보 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["UserResponse"];
                };
            };
            /** @description 미인증 상태 (Spring Security) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    removeMember_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                memberId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 제거 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 생성자 본인 제거 시도 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 호출자가 워크스페이스 생성자 아님 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 워크스페이스 없음 또는 workspace_member row 없음 / 다른 워크스페이스 소속 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                ruleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 기본 제공 룰 삭제 시도 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 룰 없음 또는 다른 프로젝트 소속 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rejectProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                proposalId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 거절 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 제안 없음 또는 다른 프로젝트 소속 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteEdge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                edgeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 엣지 없음 또는 다른 프로젝트 소속 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 로그아웃 완료 — 세션 무효화 및 쿠키 만료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
